### PR TITLE
Update dependencies to remove deprecation warnings

### PR DESCRIPTION
**Pull request by drewolson**
Move to new packages or new modules to remove deprecation warnings:

- **Move from gleam/iterator to gleam/yielder**
- **Move from gleam/regex to gleam/regexp**
- **Move from gleam/string_builder to gleam/string_tree**

### CODE REVIEW

**Comment by mooreryan** [comment]
Hi @drewolson, thanks for taking the time to go through this.  It looks like some of the diffs are including formatting changes.  Could you please remove those?

I thought this may be due to you having used a different gleam version than the one that was used when the files were committed.  However, I've just tried the formatter with gleam 1.6.3 and it did change the formatting on my local repo, so it I'm thinking it may be something else.

**Comment by drewolson** [comment]
Done. Apologies, my editor automatically removes trailing newlines.

**Comment by drewolson** [comment]
Note that I'm no longer updating all of your dependencies. You may want to do that just for development purposes, but I figured I'd keep this PR more targeted.

**Comment by mooreryan** [comment]
> Note that I'm no longer updating all of your dependencies.

Was this in the force push from about 15 minutes ago?  I didn't look closely at the changes and run the checks until after the formatting changes were removed.  It currently seems that the dependency updates are targeted to the stuff that actually changed.

**Comment by drewolson** [comment]
Yes, that’s correct.

**Comment by mooreryan** [comment]
Thanks, looks great! :sparkles:

**Pull request merged**
